name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    services:
      # Add PostgreSQL service
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      # Add Redis service
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    # Install dependencies for server
    - name: Install server dependencies
      working-directory: ./server
      run: npm ci

    # Install dependencies for client
    - name: Install client dependencies
      working-directory: ./client
      run: npm ci

    # Run server tests
    - name: Run server tests
      working-directory: ./server
      env:
        NODE_ENV: test
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/testdb
        REDIS_URL: redis://localhost:6379
      run: npm test

    # Build client
    - name: Build client
      working-directory: ./client
      run: npm run build

    # Deploy to Vercel (Frontend)
    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Deploy to Vercel
      working-directory: ./client
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      run: |
        vercel --prod --token $VERCEL_TOKEN --confirm

    # Deploy to Railway (Backend)
    - name: Install Railway CLI
      run: |
        npm install -g @railway/cli
        railway login --no-browser

    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
      run: |
        railway up --detach
